AWSTemplateFormatVersion: "2010-09-09"
Description: "Template to create EC2 instances with Security Groups, using an existing VPC and assigning specific private IPs."

Resources:
  EC2SecurityGroup1:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupName: "Matrix-Synapse"
      GroupDescription: "Security group for Matrix Synapse service"
      VpcId: !ImportValue VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: 8008
          ToPort: 8008
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: 8448
          ToPort: 8448
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: "0.0.0.0/0"

  EC2SecurityGroup2:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupName: "Wordpress-Tickets"
      GroupDescription: "Security group for Tickets Wordpress"
      VpcId: !ImportValue VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: "0.0.0.0/0"

  EC2SecurityGroup3:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupName: "Postgres-Matrix"
      GroupDescription: "Security group for Tickets Wordpress"
      VpcId: !ImportValue VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: "0.0.0.0/0"

  NetworkInterfaceMatrix:
    Type: AWS::EC2::NetworkInterface
    Properties:
      SubnetId: !ImportValue PublicSubnet1Id
      PrivateIpAddress: "10.210.1.2"
      Description: "Network Interface for Matrix-Synapse"
      GroupSet:
        - !Ref EC2SecurityGroup1
      Tags:
        - Key: Name
          Value: "Matrix-Synapse-Interface"

  NetworkInterfaceWordpress:
    Type: AWS::EC2::NetworkInterface
    Properties:
      SubnetId: !ImportValue PublicSubnet2Id
      PrivateIpAddress: "10.210.2.2"
      Description: "Network Interface for Wordpress"
      GroupSet:
        - !Ref EC2SecurityGroup2
      Tags:
        - Key: Name
          Value: "Wordpress-Interface"

  NetworkInterfacePostgres:
    Type: AWS::EC2::NetworkInterface
    Properties:
      SubnetId: !ImportValue PrivateSubnet1
      PrivateIpAddress: "10.210.3.10"
      Description: "Network Interface for Postgres"
      GroupSet:
        - !Ref EC2SecurityGroup3
      Tags:
        - Key: Name
          Value: "Postgres-Interface"

  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: "t2.micro"
      ImageId: "ami-04b4f1a9cf54c11d0"
      KeyName: "ssh-mensagl-2025-Marcos"
      NetworkInterfaces:
        - NetworkInterfaceId: !Ref NetworkInterfaceMatrix
          DeviceIndex: "0"
          AssociatePublicIpAddress: "true"
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            Encrypted: false
            DeleteOnTermination: true
            Iops: 3000
            VolumeSize: 16
            VolumeType: gp3
      Tags:
        - Key: Name
          Value: "Matrix-Synapse"

  EC2Instance2:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: "t2.micro"
      ImageId: "ami-04b4f1a9cf54c11d0"
      KeyName: "ssh-mensagl-2025-Marcos"
      NetworkInterfaces:
        - NetworkInterfaceId: !Ref NetworkInterfaceWordpress
          DeviceIndex: "0"
          AssociatePublicIpAddress: "true"
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            Encrypted: false
            DeleteOnTermination: true
            Iops: 3000
            VolumeSize: 16
            VolumeType: gp3
      Tags:
        - Key: Name
          Value: "Wordpress-Tickets"
  
  EC2Instance3:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: "t2.micro"
      ImageId: "ami-0e1bed4f06a3b463d"
      KeyName: "ssh-mensagl-2025-Marcos"
      NetworkInterfaces:
        - NetworkInterfaceId: !Ref NetworkInterfacePostgres
          DeviceIndex: "0"
          AssociatePublicIpAddress: "true"
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            Encrypted: false
            DeleteOnTermination: true
            Iops: 3000
            VolumeSize: 16
            VolumeType: gp3
      Tags:
        - Key: Name
          Value: "Postgres-Matrix"

Outputs:
  Instance1Id:
    Description: "Instance ID of the created EC2 instance"
    Value: !Ref EC2Instance1

  Instance2Id:
    Description: "Instance ID of the created EC2 instance"
    Value: !Ref EC2Instance2

  Instance2Id:
    Description: "Instance ID of the created EC2 instance"
    Value: !Ref EC2Instance3

  SecurityGroup1Id:
    Description: "Security Group ID"
    Value: !Ref EC2SecurityGroup1
  
  SecurityGroup2Id:
    Description: "Security Group ID"
    Value: !Ref EC2SecurityGroup2

  SecurityGroup2Id:
    Description: "Security Group ID"
    Value: !Ref EC2SecurityGroup3
